<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezcomments",
                     "development" => false,
                     "summary" => "ezcomments extension",
                     "description" => "This package contains the ezcomments eZ Publish extension",
                     "vendor" => false,
                     "vendor-dir" => false,
                     "priority" => false,
                     "type" => "extension",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.7.0alpha1",
                                           "named-version" => "4.7alpha1" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => 1332404076,
                                           "host" => "localhost",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "data" => "This file is part of the package ezcomments.\n\nThis package is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version.\n\nThis package is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this package; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n",
                                                  "audience" => false ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => 1332404076,
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "content" => false,
                                                "type" => "ezextension",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "extension-ezcomments",
                                                "sub-directory" => "ezextension" ) ),
                     "uninstall" => array( array( "content" => false,
                                                  "type" => "ezextension",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "extension-ezcomments",
                                                  "sub-directory" => "ezextension" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages";
?>
