{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $objectattribute.content.show_comments}
    {ezcss_require( 'comment.css' )}
    <div class="content-view-full ezcom-full">
        {include contentobject=$contentobject uri="design:comment/view_content.tpl"}
        {if $can_read}
            {include contentobject=$contentobject
                     language_id=$language_id
                     total_count=$total_count
                     total_page=$total_page
                     current_page=$current_page
                     uri="design:comment/view/page.tpl"}
            
            {if $comments|count|gt( 0 )}
                <div class="ezcom-view-list">
                    {for 0 to $comments|count|sub( 1 ) as $index}
                        {include comment=$comments.$index
                                 index=$index base_index=$current_page|sub( 1 )|mul( $number_per_page )
                                 contentobject=$contentobject
                                 language_code=$language_code
                                 uri="design:comment/view/comment_item.tpl"}
                    {/for}
                </div>
            {else}
                <div class="message-feedback">
                    <p>
                        {'There is no comment!'|i18n( 'extension/ezcomments/view' )}
                    </p>
                </div>
            {/if}
        {else}
            <div class="message-feedback">
                    <p>
                        {'You don\'t have access to view comment here!'|i18n( 'extension/ezcomments/view' )}
                    </p>
            </div>
        {/if}
        {if $objectattribute.content.enable_comment}
            {if $can_add}
                {include uri="design:comment/add_comment.tpl" redirect_uri=concat( 'comment/view/', $contentobject.id ) contentobject_id=$contentobject.id language_id=$language_id}
            {else}
                    <div class="message-feedback">
                            <p>
                                {'You don\'t have access to post comment here!'|i18n( 'extension/ezcomments/view' )}
                            </p>
                    </div>
            {/if}
        {/if}
     </div>
{/if}